### ISSUE TITLE
no main manifest attribute, in FMU-proxy.jar

### ISSUE THREAD

**Issue by vini-at-potential** [NTNU-IHB/FMU-proxy#129]
Hello,
First of all, great work! The fmu-proxify feature is awesome! Working great when running all in the localhost.

I am getting  "no main manifest attribute, in FMU-proxy.jar" both in windows 10 and Linux when I trying to "java -jar FMU-proxy.jar <port>" on the target computer.

**Comment by markaren** [comment]
Yeah, sorry about this. What you are experiencing is actually a missing feature. I did a large restructure of the project back when I implemented this as an FMU. While localhost works, I never implemented the executable that is needed for the FMU to communicate with a different computer. I'll see what I can do. Nevertheless, the jar you have right now not something you'd use for the current state of the project. It might be the jar that comes with v0.6.2, which is a legacy project and you are supposed to start the executable using the shell scripts in bin. Regardless, you are not supposed to start that particular jar in conjunction with fmu-proxify. Currently the jar you need is missing altogether. But again, I'll look into it as soon as possible.

**Comment by markaren** [comment]
I'm working towards this through #130

**Comment by vini-at-potential** [comment]
no need to be sorry, I kind of guessed that this was the problem. Thank you for opening the pull request and taking the time to look into this

**Comment by markaren** [comment]
Feature is ready now. After running `-/gradlew build` a new executable will be located at `fmu-proxy-booter/build/install`
It takes a single argument as input, which is the port to use for the booter. This is the port you reference in the `proxy-settings.txt` inside the FMU resource folder.
E.g.
```
fmu=myfmu.fmu
remote=localhost:9091
```

The booter will automatically spawn new processes on the target computer, each with a unique port number that is sent back to the proxy fmu.

**Comment by markaren** [comment]
I forgot to mention that you will need to remake the FMU itself, as the RPC interface was also updated.

**Comment by vini-at-potential** [comment]
Hey, I am not sure if I am doing something wrong but now it doesn't work even in the localhost. When running a co-simulation (CS) implementation I am getting:

fmiModelDescription
  fmiVersion=2.0
  modelName=bouncingBall-proxy
  guid=74af3284-2cf8-489c-bf06-94d83112a7f0
CoSimulation
  modelIdentifier=bouncingBall-proxy
  canBeInstantiatedOnlyOncePerProcess=false
  canNotUseMemoryManagementFunctions=true
error: Could not load C:\Users\vinicius\AppData\Local\Temp\fmu\binaries\win64\bouncingBall-proxy.dll

When trying a model exchange (ME) it fails during the proxify set :

fmu-proxify bouncingBall.fmu -r localhost:9090
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at no.ntnu.ihb.fmi4j.FmuBuilder.build(FmuBuilder.kt:58)
        at no.ntnu.ihb.fmuproxy.FmuProxifier.build(FmuProxifier.kt:45)
        at no.ntnu.ihb.fmuproxy.FmuProxifier$Args.run(FmuProxifier.kt:74)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at no.ntnu.ihb.fmuproxy.FmuProxifier$Companion.main(FmuProxifier.kt:82)
        at no.ntnu.ihb.fmuproxy.FmuProxifier.main(FmuProxifier.kt)
Caused by: java.lang.NullPointerException: md.coSimulation must not be null
        at no.ntnu.ihb.fmuproxy.FmuWrapper.processFmi2ModelDescription(FmuWrapper.kt:194)
        at no.ntnu.ihb.fmuproxy.FmuWrapper.registerVariables(FmuWrapper.kt:125)
        at no.ntnu.ihb.fmi4j.export.fmi2.Fmi2Slave.__define__(Fmi2Slave.kt:457)
        ... 16 more

**Comment by vini-at-potential** [comment]
The booter server seems to be running, I could telnet into it. I tried with and without the booter server without success.

I told I am not sure if I am doing something wrong because even when I git reset to the commit I first tested I am not able to make it work in the localhost anymore, so I might have problems on my side. 

The FMU I am trying to proxify is just the bouncingBall.fmu example from the [fmusdk](https://github.com/qtronic/fmusdk).

**Comment by markaren** [comment]
Which tool do you run the FMU in?
Are there more than one FMUs loaded in the simulation tool. If so, are they by any chance generated by FMI4j?

> error: Could not load C:\Users\vinicius\AppData\Local\Temp\fmu\binaries\win64\bouncingBall-proxy.dll

That path is strange..



> When trying a model exchange (ME) it fails during the proxify step:

ME is unsupported so an error here is expected. A better error message could be implemented though.

**Comment by markaren** [comment]
Try a `gradlew clean build` also. Perhaps the build caching is keeping some files.

**Comment by vini-at-potential** [comment]
The tool I am running is a simple C solver provided in the [fmusdk](https://github.com/NTNU-IHB/FMU-proxy/issues/129)

The fmu runs ok when not proxified.

The `gradlew clean build` did not work

**Comment by markaren** [comment]
Would you mind testing the FMU using e.g. fmpy.gui? Also, could you upload the FMU here so I wont have to compile it myself? Can have a look tommorrow evening. However, when you are building this project you are also running the tests, which I assume passes, so then at least the test fmus work.

**Comment by vini-at-potential** [comment]
[fmusim_20_cs.zip](https://github.com/NTNU-IHB/FMU-proxy/files/6410398/fmusim_20_cs.zip)

Here is the tool compiled for Win64.
The tool is able to run the test examples of your project without problems.

**Comment by vini-at-potential** [comment]
Also, take your time to solve this issue, I already have a solution to the problem I was trying to solve in the first place, so now I am just feeding you with information to debug this.

**Comment by vini-at-potential** [comment]
With fmpy.gui I got:
Failed to load shared library C:\Users\vinicius\AppData\Local\Temp\tmpdsni7fgi\binaries\win64\bouncingBall-proxy.dll. Could not find module 'C:\Users\vinicius\AppData\Local\Temp\tmpdsni7fgi\binaries\win64\bouncingBall-proxy.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by vini-at-potential** [comment]
The example FMUs in your projects also returns the same errors.

And this is what I got in Linux (Ubuntu 20.04):

fmusim_20_cs ControlledTemperature-proxy.fmu
cmd='unzip -o -d fmuTmpcikj4r/ "ControlledTemperature-proxy.fmu" > /dev/null'
fmiModelDescription
  fmiVersion=2.0
  modelName=ControlledTemperature-proxy
  guid=2dbf6fa8-2579-4f63-99bd-f15fb67e50cc
CoSimulation
  modelIdentifier=ControlledTemperature-proxy
  canBeInstantiatedOnlyOncePerProcess=false
  canNotUseMemoryManagementFunctions=true
dllPath = fmuTmpcikj4r/binaries/linux64/ControlledTemperature-proxy.so
FMU Simulator: run 'ControlledTemperature-proxy.fmu' from t=0..1 with step size h=0.1, loggingOn=0, csv separator=',' log categories={ }
[FMI4j native] Created a new JVM.
Exception in thread "main" java.lang.ClassNotFoundException: 
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
fatal ControlledTemperature-proxy (): [FMI4j native] Unable to find class ''!
could not instantiate model

In linux I am using  openjdk 8, more specifically version 1.8.0_292
In windows I am using oracle java, version 1.8.0_291

**Comment by markaren** [comment]
[ControlledTemperature-proxy.zip](https://github.com/NTNU-IHB/FMU-proxy/files/6410859/ControlledTemperature-proxy.zip)

Can you try this proxied version of ControlledTemperature generated on my machine on your end?

For some reason though, half of the team members at the lab in Ålesund is not able to run proxified FMUs. They are not able to debug the issue themselves, so I kinda don't know what the specific cause is. However they fail with a Thrift exception so it may not be related.

**Comment by markaren** [comment]
On linux with JDK 11 I do get a error related to JAXB, though. Thought I had that figured out. Will fix that at least. On JDK8 it should be fine though. The CI builds for JDK8 on linux and windows. Guess I should update the build matrix to include JDK 11.

**Comment by markaren** [comment]
Mhh.. I does not want to work on JDK11 even though FMI4j itself builds on JDK11. It's strange.
However, on my win PC, Ubuntu on WSL and on the GithUb CI (win & ubuntu) it works fine. Dunno what happens on your end.

**Comment by markaren** [comment]
Also note that there is https://github.com/open-simulation-platform/proxy-fmu, which might act as an alternative. It does not depend on a JVM. It does however, not function as an FMU, but there is a easy to use client implemented that is available though conan.

**Comment by markaren** [comment]
Just tried this feature on a fresh Windows PC and it seems to work. The readme was wrong though, the correct command for starting the booter (when targeting the FMU to run on something different that localhost) is simply `./fmu-proxy-booter <port>`
