### ISSUE TITLE
Add Windows CI for C++ project

### ISSUE THREAD

**Issue by markaren** [NTNU-IHB/FMU-proxy#70]
https://www.appveyor.com/ is an option.
BUT
The initial un-cached run will take over 60 minutes, making the (free plan) build fail. I had the same problem with CircleCI (out-of-memory). The solution there was to use a docker image.

**Comment by traversaro** [comment]
[Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) is a relatively new free (for open source) service that does not have the 60 minutes limit, it may be worth checking it out. 
The Point Cloud Library recently switched to it exactly for the more convenient time limits: https://github.com/PointCloudLibrary/pcl/issues/2554 .

**Comment by markaren** [comment]
Thanks, looking into it!

**Comment by markaren** [comment]
Having some issue with this one. Until they get caching in-place it is pretty much unusable. The vcpkg run will take about 110 minutes each time!

Conan has it's own issues, where it seems to fail on downloading one or more of the required dependencies.. 

Putting this on hold.

**Comment by markaren** [comment]
Closed somewhat by #93. However, it only builds for vcpkg as the conan build gives a mysterious error.
